- name: Clickhouse download amd64 packages
  become: true
  ansible.builtin.get_url:
    url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_amd64.deb"
    dest: ./{{ item }}_{{ clickhouse_version }}_amd64.deb
    mode: 0644
  with_items: "{{ clickhouse_amd64_packages }}"
- name: Clickhouse. Install clickhouse-common-static
  become: true
  ansible.builtin.apt:
    deb: ./clickhouse-common-static_{{ clickhouse_version }}_amd64.deb
  notify: Start clickhouse service
- name: Clickhouse. Install clickhouse-client
  become: true
  ansible.builtin.apt:
    deb: "./clickhouse-client_{{ clickhouse_version }}_amd64.deb"
  notify: Start clickhouse service
- name: Clickhouse. Install clickhouse-server
  become: true
  ansible.builtin.apt:
    deb: ./clickhouse-server_{{ clickhouse_version }}_amd64.deb
  notify: Start clickhouse service
- name: Clickhouse. Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Clickhouse. Waiting while clickhouse-server is available...
  ansible.builtin.pause:
    seconds: 20
- name: Create database
  ansible.builtin.command: "clickhouse-client -q 'create database log4;'"
  register: create_db
  failed_when: create_db.rc != 0 and create_db.rc != 83
  changed_when: create_db.rc == 0
  retries: 10
  delay: 3
  until: create_db.rc == 0 or create_db.rc == 83